---

name: Issue labeler
on:
  issues:
    types: [ opened ]

permissions:
  contents: read

jobs:
  label-component:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    strategy:
      matrix:
        template: [ issue-template.yml ]

    steps:
      - uses: actions/checkout@7cdaf2fbc075e6f3b9ca94cfd6cec5adc8a75622

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@96f2b64808e8d528b0d06a67b98db39335861a79
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/${{ matrix.template }}

      - name: Set labels based on type input
        uses: redhat-plumbers-in-action/advanced-issue-labeler@8ed038ae42158ffd94c467565e4648f46763b94d
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          token: ${{ secrets.GITHUB_TOKEN }}

...
