---

name: Linting suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@7cdaf2fbc075e6f3b9ca94cfd6cec5adc8a75622

      - name: Use Node.js 18.x
        uses: actions/setup-node@2a017f350dbf6c4b6bb4508cc83809719115162e
        with:
          node-version: 18
          cache: yarn

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Prettier
        run: yarn run format-check

      - name: ESLint
        run: yarn run lint

...
