---

name: Linting suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@7cdaf2fbc075e6f3b9ca94cfd6cec5adc8a75622
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@ae3c77f45b03c6e02021b04fd62abf51046434a0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_TYPESCRIPT_STANDARD: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@7cdaf2fbc075e6f3b9ca94cfd6cec5adc8a75622

      - name: Use Node.js 18.x
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8
        with:
          node-version: 18
          cache: yarn

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Prettier
        run: yarn run format-check

      - name: ESLint
        run: yarn run lint

...
