---

name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Unit Tests - Node.js
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]

    steps:
      - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@962678f22cdec338fba2a277a33cf81d5e28f7b9
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install
        run: yarn install

      - name: Compile
        run: yarn build

      - name: Package
        run: yarn run package

      - name: Test
        run: yarn test

      - name: Codecov
        if: ${{ matrix.node-version == '18.x' }}
        uses: codecov/codecov-action@4b062cb89c1fe1fd7da7e013d554a088ea14178a

...
